#!/usr/bin/env perl

use strict;
use warnings;

use Path::Class;

chdir 'Search-Kino030';
my $dir;

{
    system "ack -f --perl lib boilerplater t | xargs perl -p -i -e's/KinoSearch::/Search::Kino030::KinoSearch::/g'";
    system "ack -f --perl lib boilerplater t | xargs perl -p -i -e's/KSx::/Search::Kino030::KSx::/g'";
    system "ack -f --perl lib | xargs perl -p -i -e's/use KinoSearch/use Search::Kino030::KinoSearch/g'";

    my $dir = dir 'lib/Search/Kino030';
    $dir->mkpath;
    system "cd lib && mv K* Search/Kino030";
}

{
    system "find core -name '*.bp' | xargs perl -p -i -e's/KinoSearch::/Search::Kino030::KinoSearch::/g'";
    system "find core -name '*.bp' | xargs perl -p -i -e's/KSx::/Search::Kino030::KSx::/g'";

    system "find core -name '*.bp' | xargs perl -p -i -e's/parcel KinoSearch/parcel Search::Kino030::KinoSearch/g'";
    system "find core -name '*.bp' | xargs perl -p -i -e's/parcel KSx/parcel Search::Kino030::KSx/g'";

    system "find core -name '*.bp' | xargs perl -p -i -e's{KinoSearch/}{Search/Kino030/KinoSearch/}g'";
    system "find core -name '*.bp' | xargs perl -p -i -e's{KSx/}{Search/Kino030/KSx/}g'";

    system "ack -f --c core | xargs perl -p -i -e's{KinoSearch/}{Search/Kino030/KinoSearch/}g'";
    system "ack -f --c core | xargs perl -p -i -e's{KSx/}{Search/Kino030/KSx/}g'";

    my $dir = dir 'core/Search/Kino030';
    $dir->mkpath;
    system "cd core && mv K* Search/Kino030";
}

{
    system "ack -f --c xs | xargs perl -p -i -e's{KinoSearch/}{Search/Kino030/KinoSearch/}g'";
    system "ack -f --c xs | xargs perl -p -i -e's{KSx/}{Search/Kino030/KSx/}g'";

    system "ack -f --perl boilerplater | xargs perl -p -i -e's{KinoSearch/}{Search/Kino030/KinoSearch/}g'";
    system "ack -f --perl boilerplater | xargs perl -p -i -e's{KSx/}{Search/Kino030/KSx/}g'";

    my $dir = dir 'xs/Search/Kino030';
    $dir->mkpath;
    system "cd xs && mv KinoSearch Search/Kino030";

    dir('Search/Kino030')->mkpath
}

system "perl -p -i -e's{KinoSearch.pm}{Search/Kino030/KinoSearch.pm}g' Build.PL";
system q[perl -p -i -e"s{'KinoSearch'}{'Search::Kino030::KinoSearch'}g" Build.PL];
system "perl -p -i -e's{KinoSearch[./\\\$](?!bs|\\\$)}{Search/Kino030/\$&}g' buildlib/Lucy/Build.pm";
#system "perl -p -i -e's{KINO_ Kino_ kino_}{SK030_KINO_ SK030_Kino_ SK030_kino_}g' buildlib/Lucy/Build.pm";
system "perl -p -i -e's{lib KinoSearch}{lib Search Kino030 KinoSearch}g' buildlib/Lucy/Build.pm";
system "perl -p -i -e's{KinoSearch::Redacted}{Search::Kino030::KinoSearch::Redacted}g' buildlib/Lucy/Build.pm";
#system q[perl -p -i -e"s{'auto', 'KinoSearch'}{'auto', 'Search', 'Kino030', 'KinoSearch'}g" buildlib/Lucy/Build.pm];

#for (qw/KINO Kino kino/) {
#    system "find . -name '*.bp' -or -name '*.c' -or -name '*.xs' -or -name '*.h' | xargs perl -p -i -e's/${_}_/SK030_${_}_/g'";
#}

1;
